title: Leedham and Associates
description: Practical Technology Solutions for Modern Organizations

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

url: "https://paulleedham74.github.io"
baseurl: "/paulleedham74-landaIT"

minimal_mistakes_skin: default
logo: null

atom_feed:
  hide: true

search: false
breadcrumbs: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
